### ISSUE TITLE
Unknown column 'dependency_id'

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#580]
```
Apr 28, 2016 10:21:44 PM org.apache.catalina.core.StandardWrapperValve invoke
INFO: Apr 28, 2016 10:21:44 PM org.apache.catalina.core.ApplicationContext log
INFO:
ActiveRecord::StatementInvalid (ActiveRecord::JDBCError: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'dependency_id' in 'order clause': SELECT `tasks`.* FROM `tasks` WHERE `tasks`.`id` IN (78, 11705, 15659, 25022, 25683, 20140, 27691, 28211, 27959, 27950, 28382, 27977, 28169, 27916, 28179, 28180, 28358, 28183, 27146, 28505, 28890, 28035, 28029, 28542, 28454, 28692, 28544, 28727, 28784, 28379, 28750, 28782, 28806, 28819, 17618, 28401, 21118, 28322, 28653, 28621, 28928, 28811, 28931, 28557, 28974, 16346, 24245, 23928, 27504, 27644, 27693, 24338, 25610, 25556, 25591, 28929, 27215, 28090, 28646, 28683)  ORDER BY dependency_id):
  app/controllers/widgets_controller.rb:168:in `tasks_extracted_from_show'
  app/controllers/widgets_controller.rb:26:in `show'
```

**Comment by ari** [comment]
A user has reported this:

Browse console error
'/tasks/dependency/?dependency_id=28173 Failed to load resource: the server responded with a status of 404 (Not Found)'

When I enter any task in 'Snooze until', the popup shows this task, but I can not add it to this list

**Comment by ari** [comment]
Do you need help reproducing this bug?

**Comment by k41n** [comment]
I've just reproduced it. I'm working on this issue.
