### ISSUE TITLE
Logstash not working

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#597]
Error from logstash's logs.

`{:timestamp=>"2016-05-13T14:43:05.974000+1000", :message=>"Lumberjack input: unhandled exception", :exception=>#<RuntimeError: unsupported protocol 123>, :backtrace=>["/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:225:in `handle_version'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:210:in `header'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in `feed'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:332:in `read_socket'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:315:in `run'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.7/lib/logstash/inputs/lumberjack.rb:144:in `invoke'", "org/jruby/RubyProc.java:281:in `call'", "/usr/local/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.2-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_1598968526.gen:13:in `run'"], :level=>:error}`

**Comment by ari** [comment]
I'm guessing you aren't using the lumberjack input but something else.

**Comment by ari** [comment]
Never mind, I figured out the settings.
